### ISSUE TITLE
[Suggestion] Add sorting annotations

### ISSUE THREAD

**Issue by Biquaternions** [J4C0B3Y/ConfigAPI#1]
An annotation like `@AlwaysAtTop` to keep certain information like "version" always at the top of the file will be useful.
Preventing this from happening, `info` should be at top (it is declared at the top in the code):

![Image](https://github.com/user-attachments/assets/8544b9c6-2ef6-4e15-b1d3-cd0a48820bf7)

An even better (probably unnecessary) alternative, an annotation like `@Order(int index)`
To specify an order to use in the config

**Comment by J4C0B3Y** [comment]
If its declared is at the top of the code, it will be at the top of the document unless configHandler.setFormatStructure(false) is set, do you have it set to false?

With the order annotation, not sure how i could do that as currently im recursively looping through child classes and fields, so i cant really control the order.

**Comment by Biquaternions** [comment]
Nope, I haven't set it to false, and the default value is set to true
Btw, I noticed that its prioritizing individual fields over the static classes, "info" is still the first of all the classes, but all the individual values moved at the top.
Since those are probably separated loops, I'm not sure if there's something that could be done about it tho

I'll attach the resulting yml so you can take a look, all the classes appear sorted, but at the bottom.
```yml
# Pufferfish Configuration
# Check out Pufferfish Host for maximum performance server hosting: https://pufferfish.host
# Join our Discord for support: https://discord.gg/reZw4vQV9H
# Download new builds at https://ci.pufferfish.host/job/Pufferfish

# Whether or not books should be writeable.
# Servers that anticipate being a target for duping may want to consider
# disabling this option.
# This can be overridden per-player with the permission pufferfish.usebooks
enable-books: true

# Optimizes the suffocation check by selectively skipping
# the check in a way that still appears vanilla. This should
# be left enabled on most servers, but is provided as a
# configuration option if the vanilla deviation is undesirable.
enable-suffocation-optimization: true

# Whether or not asynchronous mob spawning should be enabled.
# On servers with many entities, this can improve performance by up to 15%. You must have
# paper's per-player-mob-spawns setting set to true for this to work.
# One quick note - this does not actually spawn mobs async (that would be very unsafe).
# This just offloads some expensive calculations that are required for mob spawning.
enable-async-mob-spawning: true

# Throttles the AI goal selector in entity inactive ticks.
# This can improve performance by a few percent, but has minor gameplay implications.
inactive-goal-selector-throttle: true

# If this setting is true, the server will run faster after a lag spike in
# an attempt to maintain 20 TPS. This option (defaults to true per
# spigot/paper) can cause mobs to move fast after a lag spike.
tps-catchup: true

# Allows end crystals to respawn the ender dragon.
# On servers that expect end crystal fights in the end dimension, disabling this
# will prevent the server from performing an expensive search to attempt respawning
# the ender dragon whenever a player places an end crystal.
allow-end-crystal-respawn: true

# Sentry DSN for improved error logging, leave blank to disable
# Obtain from https://sentry.io/
sentry-dsn: ""
info:
  version: "1.0"

# Optimizes projectile settings
projectile:
  # Controls how many chunks are allowed
  # to be sync loaded by projectiles in a tick.
  max-loads-per-tick: 10

  # Controls how many chunks a projectile
  # can load in its lifetime before it gets
  # automatically removed.
  max-loads-per-projectile: 10

# Configures Flare, the built-in profiler
flare:
  # Sets the server to use for profiles.
  url: "https://flare.airplane.gg"

# Settings for things that don't belong elsewhere
misc:
  disable-method-profiler: true

# Options for connecting to Pufferfish/Airplane's online utilities
web-services:
  token: ""

# Optimizes entity brains when
# they're far away from the player
dab:
  enabled: true

  # This value determines how far away an entity has to be
  # from the player to start being effected by DEAR.
  start-distance: 12

  # This value defines how often in ticks, the furthest entity
  # will get their pathfinders and behaviors ticked. 20 = 1s
  max-tick-freq: 20

  # This value defines how much distance modifies an entity's
  # tick frequency. freq = (distanceToPlayer^2) / (2^value)
  # If you want further away entities to tick less often, use 7.
  # If you want further away entities to tick more often, try 9.
  activation-dist-mod: 8

  # A list of entities to ignore for activation
  blacklisted-entities: []
```
